#!/usr/bin/env python3

import sys
import math

def help():
    print("USAGE")
    print("    ./107transfer [num den]+")
    print("DESCRIPTION")
    print("    num     polynomial numerator defined by its coefficients")
    print("    den     polynomial denominator defined by its coefficients")

def is_valid_poly(s):
    if not s:
        return False
    for i in s:
        if i not in "*-0123456789":
            return False
    for i, ch in enumerate(s):
        if ch == '*' and (i == 0 or i == len(s) - 1 or s[i - 1] == '*' or s[i + 1] == '*'):
            return False
    return True

def polynome(y, x):
    index = 0
    result = 0
    coeff = y.split("*")
    coeff=[ int(c) for c in coeff]
    for i in coeff:
        result += int(i)*(x**index)
        index += 1
    return result

def function(argv, x):
    num = 1
    den = 1
    for i in range(1,len(argv), 2):
        num = num * polynome(argv[i],x)
    for j in range(2,len(argv), 2):
        den = den * polynome(argv[j],x)
        if den == 0:
            exit(84)
    return num / den

def transfer(argv):
    i = 0.000
    while i <= 1.001:
        x = function(argv, i)
        # if abs(x) < 10**(-5):
        #     print(f"{i:.3f} -> 0.00000")
        # else:
        print(f"{i:.3f} -> {x:.5f}")
        i += 0.001
    exit(0)

def main(argv):
    if len(argv) == 2 and argv[1] == "-h":
        help()
        exit(0)
    if len(argv) == 1:
        exit(84)
    if (len(argv) - 1) % 2 != 0:
        exit(84)
    for i in argv[1:]:
        if not is_valid_poly(i):
            exit(84)
    transfer(argv)
    exit(84)

main(sys.argv)