#!/usr/bin/env python3

import sys

def help():
    print("USAGE")
    print("    ./106bombyx n [k | i0 i1]")
    print("DESCRIPTION")
    print("    n       number of first generation individuals")
    print("    k       growth rate from 1 to 4")
    print("    i0      initial generation (included)")
    print("    i1      final generation (included)")

def basic_case(argv):
    i = 1
    n = float(argv[1])
    k = float(argv[2])
    if k < 1 or k > 4:
        exit(84)
    while i <= 100:
        if n <= 0:
            print(f"{i} 0.00")
        else:
            print(f"{i} {n:.2f}")
        n = k * n * (1000 - n) / 1000
        i += 1

def complex_case(argv):
    for i in range(2, 4):
        try:
            tmp = int(argv[i])
        except ValueError:
            exit(84)
    if int(argv[2]) > int(argv[3]) or int(argv[2]) < 1 or int(argv[3]) < 1:
        exit(84)
    n = float(argv[1])
    i0 = int(argv[2])
    i1 = int(argv[3])
    for t in range(100, 401):
        k = t / 100.0
        x = n
        for i in range(1, i1 + 1):
            if i >= i0:
                print(f"{k:.2f} {x:.2f}")
            x = k * x * (1000 - x) / 1000

def error(argv, l):
    try:
        tmp = int(argv[1])
    except ValueError:
        exit(84)
    for i in range(2, l):
        try:
            tmp = float(argv[i])
        except ValueError:
            exit(84)

def main(argv):
    l = len(argv)
    if l == 1:
        exit(84)
    error(argv, l)
    if int(argv[1]) < 0:
        exit(84)
    if l == 2 and argv[1] == "-h":
        help()
        exit(0)
    if l == 2:
        exit(84)
    if l == 3:
        basic_case(argv)
        exit(0)
    if l == 4:
        complex_case(argv)
        exit(0)
    exit(84)

main(sys.argv)