#!/usr/bin/env python3
import sys

import sys
from math import pi, cos, sin

def vector(x : float, y : float):
    return [x, y, 1]

def translation_matrix(i : float, j : float):
    print(f"Translation along vector ({int(i)}, {int(j)})")
    return [[1, 0, i], [0, 1, j], [0, 0, 1]]

def scaling_matrix(m :float, n : float):
    print(f"Scaling by factors {int(m)} and {int(n)}")
    return [[m, 0, 0], [0, n, 0], [0, 0, 1]]

def rotation_matrix(r : float):
    rad = r * pi / 180
    print(f"Rotation by a {int(r)} degree angle")
    return [[cos(rad), -sin(rad), 0], [sin(rad), cos(rad), 0], [0, 0, 1]]

def reflection_matrix(r : float):
    rad = r * pi / 180
    print(f"Reflection over an axis with an inclination angle of {int(r)} degrees")
    return [[cos(2 * rad), sin(2 * rad), 0], [sin(2 * rad), -cos(2 * rad), 0], [0, 0, 1]]

def mult_matrix(matrix : list, vector_1 : list):
    matrix_final = [0 for j in range(3)]
    for i in range(3):
        matrix_final[i] = (float(matrix[i][0]) * float(vector_1[0])) +  (float(matrix[i][1]) * float(vector_1[1])) +  (float(matrix[i][2]) * float(vector_1[2]))
    return matrix_final

def mult_2_matrix(matrix_1 : list, matrix_2 : list):
    matrix_final = [[0 for i in range(3)] for j in range(3)]
    for i in range(3):
        for j in range(3):
            matrix_final[i][j] = float(matrix_1[i][0]) * float(matrix_2[0][j]) + float(matrix_1[i][1]) * float(matrix_2[1][j]) + float(matrix_1[i][2]) * float(matrix_2[2][j])
        k = 0
    return matrix_final

def abs_zero(nb):
    if abs(nb) < 0.01:
        nb = 0.00
    return nb

def help():
   print("USAGE\n    ./102architect x y transfo1 arg11 [arg12] [transfo2 arg21 [arg22]] ...\n\n\nDESCRIPTION\n    x   abscissa of the original point\n    y   ordinate of the original point\n    transfo arg1 [arg2]\n    -t i j  translation along vector (i, j)\n    -z m n  scaling by factors m (x-axis) and n (y-axis)\n    -r d    rotation centered in O by a d degree angle\n    -s d    reflection over the axis passing through O with an inclination\n            angle of d degrees")

def main(argv : list):
    if len(argv) == 1:
        exit(84)
    if len(argv) == 2 and str(argv[1]) == "-h":
        help()
        exit(0)
    if len(argv) < 5:
        exit(84)

    matrix = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    i = 3
    while i < len(argv):
        if argv[i] == "-t":
            if len(argv) < 6:
                exit(84)
            try:
                tmp = float(argv[1])
                tmp = float(argv[2])
                tmp = float(argv[i + 1])
                tmp = float(argv[i + 2])
            except ValueError:
                exit(84)
            matrix = mult_2_matrix(translation_matrix(float(argv[i + 1]), float(argv[i + 2])), matrix)
            i += 3
        elif argv[i] == "-z":
            if len(argv) < 6:
                exit(84)
            try:
                tmp = float(argv[1])
                tmp = float(argv[2])
                tmp = float(argv[i + 1])
                tmp = float(argv[i + 2])
            except ValueError:
                exit(84)
            matrix = mult_2_matrix(scaling_matrix(float(argv[i + 1]), float(argv[i + 2])), matrix)
            i += 3
        elif argv[i] == "-r":
            try:
                tmp = float(argv[1])
                tmp = float(argv[2])
                tmp = float(argv[i + 1])
            except ValueError:
                exit(84)
            matrix = mult_2_matrix(rotation_matrix(float(argv[i + 1])), matrix)
            i += 2
        elif argv[i] == "-s":
            try:
                tmp = float(argv[1])
                tmp = float(argv[2])
                tmp = float(argv[i + 1])
            except ValueError:
                exit(84)
            matrix = mult_2_matrix(reflection_matrix(float(argv[i + 1])), matrix)
            i += 2
        else:
            exit(84)
    print(f"{abs_zero(float(matrix[0][0])):.2f}\t{abs_zero(float(matrix[0][1])):.2f}\t{abs_zero(float(matrix[0][2])):.2f}")
    print(f"{abs_zero(float(matrix[1][0])):.2f}\t{abs_zero(float(matrix[1][1])):.2f}\t{abs_zero(float(matrix[1][2])):.2f}")
    print(f"{abs_zero(float(matrix[2][0])):.2f}\t{abs_zero(float(matrix[2][1])):.2f}\t{abs_zero(float(matrix[2][2])):.2f}")
    result = mult_matrix(matrix, vector(argv[1], argv[2]))
    print(f"({abs_zero(float(argv[1])):.2f}, {abs_zero(float(argv[2])):.2f}) => ({abs_zero(float(result[0])):.2f}, {abs_zero(float(result[1])):.2f})")
    return 0



main(sys.argv)
