#!/usr/bin/env python3

import sys
import math

def change_key(key : str):
    len_matrix = math.ceil(math.sqrt(len(key)))
    matrix = [[0 for i in range(len_matrix)] for j in range(len_matrix)]
    a = 0
    for i in range(len_matrix):
        for j in range(len_matrix):
            if a < len(key):
                matrix[i][j] = ord(key[a])
                a += 1
    return matrix, len_matrix

def change_message(message : str, len_matrix : int):
    a = len(message)
    while a % len_matrix != 0:
        a += 1
    matrix = [[0 for i in range(len_matrix)] for j in range(a // len_matrix)]
    k = 0
    for i in range(a // len_matrix):
        for j in range(len_matrix):
            if k < len(message):
                matrix[i][j] = ord(message[k])
                k += 1
    return matrix

def change_crypr(message: str, len_matrix : int):
    a = 0
    for i in range(len(message)):
        if message[i] == " ":
            a += 1
    a += 1
    while a % len_matrix != 0:
        a += 1
    k = 0
    matrix = [[0 for i in range(len_matrix)] for j in range(a // len_matrix)]
    for i in range(a // len_matrix):
        for j in range(len_matrix):
            while k < len(message) and message[k] != " ":
                matrix[i][j] = matrix[i][j] * 10
                matrix[i][j] = matrix[i][j] + int(message[k])
                k += 1
            if k < len(message) and message[k] == " ":
                k += 1
    return matrix

def mult_matrix(matrix1 : list, matrix2 : list):
    if len(matrix1[0]) != len(matrix2):
        print("error mult")
        exit(84)
    matrix_final = [[0 for i in range(len(matrix2[0]))] for j in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix1[0])):
                matrix_final[i][j] += matrix1[i][k] * matrix2[k][j]
    return matrix_final

def inverse_gauss(matrix):
    n = len(matrix)
    aug = [row[:] + [float(i == j) for j in range(n)] for i, row in enumerate(matrix)]
    for i in range(n):
        if aug[i][i] == 0:
            for k in range(i + 1, n):
                if aug[k][i] != 0:
                    aug[i], aug[k] = aug[k], aug[i]
                    break
            else:
                print("error")
                exit(84)
        pivot = aug[i][i]
        if pivot == 0:
            exit(84)
        aug[i] = [x / pivot for x in aug[i]]
        for j in range(n):
            if j != i:
                ratio = aug[j][i]
                aug[j] = [aug[j][k] - ratio * aug[i][k] for k in range(2 * n)]
    inverse = [row[n:] for row in aug]
    return inverse

def abs_zero(nb):
    if abs(nb) < 0.001:
        nb = 0.0
    return nb

def help():
    print("USAGE\n    ./103cipher message key flag\n\n\nDESCRIPTION\n    message     a message, made of ASCII characters\n    key         the encryption key, made of ASCII characters\n    flag        0 for the message to be encrypted, 1 to be decrypted")

def encrypt(argv):
    matrix, len_matrix = change_key(argv[2])
    print("Key matrix:")
    for row in matrix:
        print("\t".join(str(x) for x in row))
    print("")
    matrix = mult_matrix(change_message(argv[1], len_matrix), matrix)
    print("Encrypted message:")
    print(" ".join(str(x) for row in matrix for x in row))
    exit(0)

def decrypt(argv):
    matrix, len_matrix = change_key(argv[2])
    matrix = inverse_gauss(matrix)
    print("Key matrix:")
    for row in matrix:
        print("\t".join(f"{abs_zero(x):.3f}" for x in row))
    print("")
    matrix = mult_matrix(change_crypr(argv[1], len_matrix), matrix)
    print("Decrypted message:")
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if 32 <= round(matrix[i][j]) <= 127:
                print(chr(int(round(matrix[i][j]))), end="")
    print("")
    exit(0)

def main(argv):
    if len(argv) == 2 and argv[1] == "-h":
        help()
        exit(0)
    if len(argv) >= 5 or len(argv) <= 3:
        exit(84)

    if argv[3] == "0":
        encrypt(argv)

    if argv[3] == "1":
        decrypt(argv)
    exit(84)

main(sys.argv)